# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
# -----------------------------------------
# Modificado por Antonio Paya
# -----------------------------------------

OrdererOrgs:

  - Name: Orderer
    Domain: antonio.com
    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: microsoft
    Domain: microsoft.antonio.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: apple
    Domain: apple.antonio.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
