version: '2'

services:
  caMicrosoft:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-microsoft
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.microsoft.antonio.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/98b84ec0cef251a29ce322e17ec5fd5c2bbb27174835bc0287e9f7ac9afc1156_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.microsoft.antonio.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/98b84ec0cef251a29ce322e17ec5fd5c2bbb27174835bc0287e9f7ac9afc1156_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/microsoft.antonio.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMicrosoft

  caApple:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-apple
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.apple.antonio.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6b51cf3167ca91d86a4df946dcdfa3d4b0b71dfdb2fc1bb32d579ab0f23722e7_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.apple.antonio.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6b51cf3167ca91d86a4df946dcdfa3d4b0b71dfdb2fc1bb32d579ab0f23722e7_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/apple.antonio.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerApple

  orderer.antonio.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.antonio.com
    container_name: orderer.antonio.com

  peer0.microsoft.antonio.com:
    container_name: peer0.microsoft.antonio.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.microsoft.antonio.com

  peer0.apple.antonio.com:
    container_name: peer0.apple.antonio.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.apple.antonio.com

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.microsoft.antonio.com:7051
      - CORE_PEER_LOCALMSPID=microsoftMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/microsoft.antonio.com/peers/peer0.microsoft.antonio.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/microsoft.antonio.com/peers/peer0.microsoft.antonio.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/microsoft.antonio.com/peers/peer0.microsoft.antonio.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/microsoft.antonio.com/users/Admin@microsoft.antonio.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    #command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.antonio.com
      - peer0.microsoft.antonio.com
      - peer0.apple.antonio.com
