NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.apple.antonio.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.apple.antonio.com-cert.pem
    OrganizationalUnitIdentifier: peer
